spring:
  application:
    name: Chat

  datasource:
    url: jdbc:postgresql://localhost:5432/spring-chat_db
    driver-class-name: org.postgresql.Driver
    username: danmih
    password: aue123

  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true

server:
  address: 0.0.0.0
  port: 8080
